/* Datos temporales: sustituir por la respuesta del catálogo PHP/MySQL en la siguiente fase. */
const PRODUCTS=[
 {id:1,name:'Calcetines técnicos Endurance',category:'Calcetines',price:12.95,oldPrice:15.95,description:'Calcetín técnico ligero para entrenamientos y carreras de cualquier distancia.',images:['assets/images/products-studio.png'],colors:['Negro','Blanco'],sizes:['S','M','L'],features:['Tejido transpirable','Refuerzo en talón y puntera','Ajuste anatómico'],rating:4.8,reviews:124,stock:18,featured:true,bestseller:true,new:false},
 {id:2,name:'Cinturón running Pace',category:'Accesorios',price:24.95,oldPrice:null,description:'Cinturón compacto para llevar lo imprescindible con estabilidad durante la carrera.',images:['assets/images/products-studio.png'],colors:['Negro','Gris'],sizes:['S','M','L'],features:['Bolsillo para móvil','Ajuste regulable','Detalles reflectantes'],rating:4.7,reviews:89,stock:12,featured:true,bestseller:true,new:true},
 {id:3,name:'Calcetines Performance Crew',category:'Calcetines',price:14.95,oldPrice:null,description:'Mayor cobertura y compresión suave para sesiones de entrenamiento exigentes.',images:['assets/images/products-studio.png'],colors:['Blanco','Negro'],sizes:['S','M','L'],features:['Canal de ventilación','Soporte de arco','Costuras suaves'],rating:4.9,reviews:56,stock:8,featured:true,bestseller:false,new:true},
 {id:4,name:'Riñonera Trail Essential',category:'Running',price:29.95,oldPrice:34.95,description:'Solución minimalista para tus rutas, con espacio organizado y acceso rápido.',images:['assets/images/products-studio.png'],colors:['Negro','Gris'],sizes:['Única'],features:['Capacidad ampliable','Cierre seguro','Material resistente'],rating:4.6,reviews:41,stock:20,featured:true,bestseller:false,new:false},
 {id:5,name:'Calcetines Recovery Light',category:'Calcetines',price:11.95,oldPrice:null,description:'Diseño fino y confortable para entrenamientos diarios.',images:['assets/images/products-studio.png'],colors:['Blanco','Azul'],sizes:['S','M','L'],features:['Fibra de secado rápido','Zona elástica','Acolchado ligero'],rating:4.5,reviews:32,stock:25,featured:false,bestseller:false,new:false},
 {id:6,name:'Banda porta-dorsal Race',category:'Accesorios',price:16.95,oldPrice:null,description:'Accesorio funcional para carreras y entrenamiento.',images:['assets/images/products-studio.png'],colors:['Negro'],sizes:['Única'],features:['Ajuste rápido','Material ligero','Compatible con geles'],rating:4.4,reviews:21,stock:15,featured:false,bestseller:false,new:true}
];
function getProduct(id){return PRODUCTS.find(product=>product.id===Number(id));}
function productCard(product){const badge=product.new?'Novedad':product.bestseller?'Más vendido':'';return `<article class="product-card"><div class="product-image-wrap">${badge?`<span class="product-tag">${badge}</span>`:''}<a href="producto.html?id=${product.id}"><img class="product-image" src="${product.images[0]}" alt="${product.name}"></a></div><div class="pt-3"><p class="product-category mb-1">${product.category}</p><a class="product-name d-block mb-1" href="producto.html?id=${product.id}">${product.name}</a><div class="rating mb-2"><span class="stars">★★★★★</span> ${product.rating.toFixed(1)} <span class="text-secondary">(${product.reviews})</span></div><div class="d-flex align-items-center gap-2 mb-3"><span class="price">${formatPrice(product.price)}</span>${product.oldPrice?`<span class="old-price">${formatPrice(product.oldPrice)}</span>`:''}</div><button class="btn btn-dark btn-sm w-100 add-card" data-id="${product.id}">Añadir al carrito</button></div></article>`;}
